"""
Auth Module - Reusable OAuth/JWT authentication for Python MCP servers.
"""

from gopher_mcp_python.auth.gopher_auth import GopherAuth
from gopher_mcp_python.auth.errors import (
    GopherAuthError,
    TokenValidationError,
    InsufficientScopesError,
    JwksError,
    ConfigurationError,
    TokenExchangeError,
)
from gopher_mcp_python.auth.scope_helpers import (
    has_scope,
    has_all_scopes,
    has_any_scope,
)
from gopher_mcp_python.ffi.auth import (
    AutoRefreshResult,
    GopherAuthClient,
    GopherAuthConfig,
    GopherOAuthClient,
    GopherSessionManager,
    GopherValidationOptions,
    RegistrationResponse,
    TokenPayload,
    TokenResponse,
    ValidationResult,
    gopher_auth_auto_refresh,
    gopher_auth_build_oidc_discovery_metadata,
    gopher_auth_build_oauth_server_metadata,
    gopher_auth_build_protected_resource_metadata,
    gopher_auth_extract_bearer_token,
    gopher_auth_extract_method,
    gopher_auth_extract_path,
    gopher_auth_url_decode,
    gopher_auth_url_encode,
    gopher_auth_validate_all_scopes,
    gopher_auth_validate_any_scopes,
    gopher_auth_validate_idp,
    gopher_create_validation_options,
    gopher_generate_www_authenticate_header,
    gopher_generate_www_authenticate_header_v2,
)

__all__ = [
    "GopherAuth",
    "GopherAuthError",
    "TokenValidationError",
    "InsufficientScopesError",
    "JwksError",
    "ConfigurationError",
    "TokenExchangeError",
    "has_scope",
    "has_all_scopes",
    "has_any_scope",
    "AutoRefreshResult",
    "GopherAuthClient",
    "GopherAuthConfig",
    "GopherOAuthClient",
    "GopherSessionManager",
    "GopherValidationOptions",
    "RegistrationResponse",
    "TokenPayload",
    "TokenResponse",
    "ValidationResult",
    "gopher_auth_auto_refresh",
    "gopher_auth_build_oidc_discovery_metadata",
    "gopher_auth_build_oauth_server_metadata",
    "gopher_auth_build_protected_resource_metadata",
    "gopher_auth_extract_bearer_token",
    "gopher_auth_extract_method",
    "gopher_auth_extract_path",
    "gopher_auth_url_decode",
    "gopher_auth_url_encode",
    "gopher_auth_validate_all_scopes",
    "gopher_auth_validate_any_scopes",
    "gopher_auth_validate_idp",
    "gopher_create_validation_options",
    "gopher_generate_www_authenticate_header",
    "gopher_generate_www_authenticate_header_v2",
]
